In [44]:
import numpy as np

In [45]:
np.zeros(15)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.ones(15)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [47]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [48]:
np.arange(10,51,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [49]:

np.arange(10,80,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [50]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:

np.diag([4,4,4])

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [52]:
np.random.rand(1)

array([0.8723055])

In [53]:
np.random.randn(50)

array([-1.47024576, -0.73258753,  0.18654675, -0.42053251, -0.20207709,
       -1.00127906,  1.72466983, -1.20550824,  0.50521691,  2.36872288,
        0.52335121, -0.11127723,  0.54703972, -0.23072358, -0.04020073,
       -0.09963839,  0.38990889,  1.36484212,  0.57185036, -1.62396385,
       -0.73875943,  1.06351765,  0.17720898, -0.50625894,  0.66010916,
        0.28471445, -0.03633129, -0.31874852, -1.3100498 ,  1.41068269,
        1.38804644, -1.11483207,  1.96988578, -3.26998509,  0.47661168,
       -0.08316429, -0.39247821, -0.86440905, -1.54704067, -0.3186171 ,
        0.95790909, -0.37739464,  0.74538418, -0.80303387,  0.89910378,
        1.45868795,  0.8401994 ,  0.34116157,  0.01361041, -1.19581205])

In [54]:

np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [55]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [56]:
m= np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

write the code which produce the output of the cell 

In [57]:
m[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [58]:
m[3,4]

20

In [59]:
m[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [60]:
m[4:,:5]

array([[21, 22, 23, 24, 25]])

In [61]:
m[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
m.sum()

325

In [63]:
m.std()

7.211102550927978

In [64]:
m.sum(axis=0)

array([55, 60, 65, 70, 75])